import {
  ExpertNetworkStore,
  ExpertNetworkWeeklyReportRecord,
} from './types';

const DOMAIN_CATALOG = [
  '农林牧渔业',
  '采矿业',
  '制造业',
  '建筑业',
  '批发和零售业',
  '交通运输、仓储和邮政业',
  '信息传输、软件和信息技术服务业',
  '金融业',
  '房地产业',
  '科学研究和技术服务业',
  '水利、环境和公共设施管理业',
  '教育',
  '卫生和社会工作',
  '文化、体育和娱乐业',
  '国际组织',
  '电力、热力、燃气及水生产和供应业',
  '居民服务、修理和其他服务业',
  '公共管理、社会保障和社会组织',
];

const demoReports: ExpertNetworkWeeklyReportRecord[] = [
  {
    id: 'expert-001',
    weekStart: '2026-04-01',
    ownerName: '王天浩',
    newExpertsCount: 96,
    weeklySubmittedCases: 104,
    totalQcPassedCases: 420,
    activeExpertsCount: 185,
    totalDomainDistribution: [
      { id: 'expert-001-total-1', domain: '教育', count: 32 },
      { id: 'expert-001-total-2', domain: '信息传输、软件和信息技术服务业', count: 24 },
      { id: 'expert-001-total-3', domain: '国际组织', count: 12 },
      { id: 'expert-001-total-4', domain: '科学研究和技术服务业', count: 18 },
      { id: 'expert-001-total-5', domain: '金融业', count: 14 },
      { id: 'expert-001-total-6', domain: '制造业', count: 15 },
      { id: 'expert-001-total-7', domain: '建筑业', count: 9 },
      { id: 'expert-001-total-8', domain: '房地产业', count: 7 },
      { id: 'expert-001-total-9', domain: '文化、体育和娱乐业', count: 6 },
      { id: 'expert-001-total-10', domain: '农林牧渔业', count: 5 },
    ],
    weeklyNewDomainDistribution: [
      { id: 'expert-001-week-1', domain: '教育', count: 26 },
      { id: 'expert-001-week-2', domain: '信息传输、软件和信息技术服务业', count: 18 },
      { id: 'expert-001-week-3', domain: '金融业', count: 9 },
      { id: 'expert-001-week-4', domain: '科学研究和技术服务业', count: 8 },
      { id: 'expert-001-week-5', domain: '制造业', count: 7 },
      { id: 'expert-001-week-6', domain: '国际组织', count: 7 },
      { id: 'expert-001-week-7', domain: '建筑业', count: 5 },
      { id: 'expert-001-week-8', domain: '房地产业', count: 4 },
      { id: 'expert-001-week-9', domain: '农林牧渔业', count: 3 },
      { id: 'expert-001-week-10', domain: '文化、体育和娱乐业', count: 3 },
    ],
    summary:
      '本周新增专家 96 人，重点补充教育、信息技术和金融三类领域，周内提交 case 104 条，质检闭环节奏基本稳定。',
    nextWeekFocus:
      '优先补足英文 case 产出专家，并把信息技术、教育两类高频领域的专家画像沉淀为复用模板。',
    remarks: '当前仍以 Excel 汇总为主，平台数据用于统一对内汇报口径。',
    status: 'submitted',
    createdAt: '2026-04-02T01:20:00.000Z',
    updatedAt: '2026-04-02T02:10:00.000Z',
  },
  {
    id: 'expert-002',
    weekStart: '2026-04-08',
    ownerName: '王天浩',
    newExpertsCount: 118,
    weeklySubmittedCases: 136,
    totalQcPassedCases: 512,
    activeExpertsCount: 224,
    totalDomainDistribution: [
      { id: 'expert-002-total-1', domain: '教育', count: 48 },
      { id: 'expert-002-total-2', domain: '信息传输、软件和信息技术服务业', count: 38 },
      { id: 'expert-002-total-3', domain: '科学研究和技术服务业', count: 22 },
      { id: 'expert-002-total-4', domain: '国际组织', count: 16 },
      { id: 'expert-002-total-5', domain: '制造业', count: 22 },
      { id: 'expert-002-total-6', domain: '金融业', count: 17 },
      { id: 'expert-002-total-7', domain: '建筑业', count: 14 },
      { id: 'expert-002-total-8', domain: '房地产业', count: 9 },
      { id: 'expert-002-total-9', domain: '交通运输、仓储和邮政业', count: 7 },
      { id: 'expert-002-total-10', domain: '批发和零售业', count: 8 },
      { id: 'expert-002-total-11', domain: '农林牧渔业', count: 7 },
      { id: 'expert-002-total-12', domain: '文化、体育和娱乐业', count: 7 },
      { id: 'expert-002-total-13', domain: '卫生和社会工作', count: 4 },
    ],
    weeklyNewDomainDistribution: [
      { id: 'expert-002-week-1', domain: '教育', count: 16 },
      { id: 'expert-002-week-2', domain: '信息传输、软件和信息技术服务业', count: 14 },
      { id: 'expert-002-week-3', domain: '制造业', count: 7 },
      { id: 'expert-002-week-4', domain: '建筑业', count: 5 },
      { id: 'expert-002-week-5', domain: '金融业', count: 3 },
      { id: 'expert-002-week-6', domain: '国际组织', count: 4 },
      { id: 'expert-002-week-7', domain: '科学研究和技术服务业', count: 4 },
      { id: 'expert-002-week-8', domain: '批发和零售业', count: 4 },
      { id: 'expert-002-week-9', domain: '交通运输、仓储和邮政业', count: 3 },
      { id: 'expert-002-week-10', domain: '农林牧渔业', count: 2 },
      { id: 'expert-002-week-11', domain: '文化、体育和娱乐业', count: 1 },
      { id: 'expert-002-week-12', domain: '卫生和社会工作', count: 1 },
    ],
    summary:
      '本周新增专家 118 人，英文 case 能力和行业覆盖面继续扩充，累计质检通过 case 已突破 500 条，活跃专家池保持增长。',
    nextWeekFocus:
      '继续补充信息技术、教育、科研领域的高质量专家，并建立“新增专家 -> case 产出 -> 质检通过”的周度追踪链路。',
    remarks: '周内新增来源仍以人工收集为主，后续会逐步切换为平台化录入。',
    status: 'submitted',
    createdAt: '2026-04-09T01:20:00.000Z',
    updatedAt: '2026-04-09T02:10:00.000Z',
  },
  {
    id: 'expert-003',
    weekStart: '2026-04-14',
    ownerName: '王天浩',
    newExpertsCount: 151,
    weeklySubmittedCases: 169,
    totalQcPassedCases: 641,
    activeExpertsCount: 263,
    totalDomainDistribution: [
      { id: 'expert-003-total-1', domain: '教育', count: 74 },
      {
        id: 'expert-003-total-2',
        domain: '信息传输、软件和信息技术服务业',
        count: 62,
      },
      { id: 'expert-003-total-3', domain: '科学研究和技术服务业', count: 33 },
      { id: 'expert-003-total-4', domain: '制造业', count: 30 },
      { id: 'expert-003-total-5', domain: '国际组织', count: 29 },
      { id: 'expert-003-total-6', domain: '金融业', count: 28 },
      { id: 'expert-003-total-7', domain: '建筑业', count: 21 },
      { id: 'expert-003-total-8', domain: '批发和零售业', count: 16 },
      { id: 'expert-003-total-9', domain: '房地产业', count: 14 },
      { id: 'expert-003-total-10', domain: '交通运输、仓储和邮政业', count: 12 },
      { id: 'expert-003-total-11', domain: '文化、体育和娱乐业', count: 12 },
      { id: 'expert-003-total-12', domain: '农林牧渔业', count: 11 },
      { id: 'expert-003-total-13', domain: '卫生和社会工作', count: 8 },
      { id: 'expert-003-total-14', domain: '采矿业', count: 7 },
      {
        id: 'expert-003-total-15',
        domain: '水利、环境和公共设施管理业',
        count: 5,
      },
    ],
    weeklyNewDomainDistribution: [
      { id: 'expert-003-week-1', domain: '农林牧渔业', count: 4 },
      { id: 'expert-003-week-2', domain: '采矿业', count: 3 },
      { id: 'expert-003-week-3', domain: '制造业', count: 8 },
      { id: 'expert-003-week-4', domain: '建筑业', count: 7 },
      { id: 'expert-003-week-5', domain: '批发和零售业', count: 4 },
      { id: 'expert-003-week-6', domain: '交通运输、仓储和邮政业', count: 3 },
      {
        id: 'expert-003-week-7',
        domain: '信息传输、软件和信息技术服务业',
        count: 24,
      },
      { id: 'expert-003-week-8', domain: '金融业', count: 11 },
      { id: 'expert-003-week-9', domain: '房地产业', count: 5 },
      { id: 'expert-003-week-10', domain: '科学研究和技术服务业', count: 12 },
      {
        id: 'expert-003-week-11',
        domain: '水利、环境和公共设施管理业',
        count: 1,
      },
      { id: 'expert-003-week-12', domain: '教育', count: 42 },
      { id: 'expert-003-week-13', domain: '卫生和社会工作', count: 2 },
      { id: 'expert-003-week-14', domain: '文化、体育和娱乐业', count: 5 },
      { id: 'expert-003-week-15', domain: '国际组织', count: 18 },
    ],
    summary:
      '本周专家网络招募新增 151 人，提交 case 169 条（当前仍待质检），新增供给继续集中在教育、信息技术、国际组织和科研领域，整体产能池扩张明显。',
    nextWeekFocus:
      '下周主要聚焦招募英文 case 产出专家及目前数据支撑量较少的领域专家，并继续提升 case 提交到质检通过的转化效率。',
    remarks:
      '本周新增领域分布合计 149 人，另有 2 人正在补充行业归类，当前看板统一按聚合数据展示，不展示个人姓名。',
    status: 'submitted',
    createdAt: '2026-04-15T01:20:00.000Z',
    updatedAt: '2026-04-15T02:10:00.000Z',
  },
];

export const demoExpertNetworkStore: ExpertNetworkStore = {
  domainCatalog: DOMAIN_CATALOG,
  reports: demoReports,
};
