import {
  PmWeeklyReportRecord,
  PmWeeklyReportsStore,
  ProjectOption,
} from './types';

export const demoPmProjects: ProjectOption[] = [
  {
    id: '3805',
    name: 'ZBZ32-语义分割',
    pmName: '李仕伟',
    curveType: '一曲线',
    annotationType: '点云分割',
    plannedQty: 128000,
    qtyUnit: '帧',
    budgetTotal: 104,
    defaultSupplier: '供应商甲',
  },
  {
    id: '40',
    name: 'zbz32-车道线',
    pmName: '张艺缤',
    curveType: '一曲线',
    annotationType: '4D车道线',
    plannedQty: 9000,
    qtyUnit: '包',
    budgetTotal: 50.8,
    defaultSupplier: '供应商甲',
  },
  {
    id: '17',
    name: 'Prosper-AGV',
    pmName: '冯德隆',
    curveType: '一曲线',
    annotationType: '2D框',
    plannedQty: 30000,
    qtyUnit: '帧',
    budgetTotal: 12,
    defaultSupplier: '供应商乙',
  },
  {
    id: 'P002',
    name: 'Mary',
    pmName: '郑威格',
    curveType: '二曲线',
    annotationType: '里程碑',
    plannedQty: 5,
    qtyUnit: '个里程碑',
    budgetTotal: 180,
    defaultSupplier: '内部研发',
  },
];

const demoPmReports: PmWeeklyReportRecord[] = [
  {
    id: 'pmr-001',
    projectId: '3805',
    projectName: 'ZBZ32-语义分割',
    pmName: '李仕伟',
    curveType: '一曲线',
    annotationType: '点云分割',
    plannedQty: 128000,
    qtyUnit: '帧',
    budgetTotal: 104,
    weekStart: '2026-04-14',
    progressPct: 87,
    actualQty: 113500,
    weeklyDeliveryAmount: 7.1,
    amountDelivered: 77.1,
    costConsumed: 91.2,
    qualityPass: 91,
    clientScore: 4.4,
    riskLevel: '绿',
    riskDesc: '本周新模型上线后整体恢复在控，仍需继续关注成本收敛。',
    blockerTitle: '客户边界样本验收规则需细化',
    blockerStatus: 'watching',
    blockerDueDate: '2026-04-24',
    suggestedAction: '安排一次客户验收规则澄清会，同时复盘剩余高成本类别。',
    supplierName: '供应商甲',
    supplierHeadcount: 12,
    supplierQuality: 94,
    supplierOtdRate: 91,
    supplierCooperation: 90,
    supplierIssue: '本周供应商质量提升明显，无新增异常。',
    algoVersion: 'v2.1',
    modificationRate: 15,
    timeSavePct: 36,
    algoAdvice: '继续降低人工新增比例，观察细分类别表现。',
    hoursSpent: 34,
    pmHourlyCost: 180,
    pmComment: '整体恢复良好，下周进入收口与质量稳态控制。',
    nextWeekFocus: '1. 成本复盘 2. 客户标准确认 3. 提前准备周报',
    status: 'submitted',
    createdAt: '2026-04-17T09:00:00.000Z',
    updatedAt: '2026-04-17T10:12:00.000Z',
  },
  {
    id: 'pmr-002',
    projectId: '40',
    projectName: 'zbz32-车道线',
    pmName: '张艺缤',
    curveType: '一曲线',
    annotationType: '4D车道线',
    plannedQty: 9000,
    qtyUnit: '包',
    budgetTotal: 50.8,
    weekStart: '2026-04-14',
    progressPct: 72,
    actualQty: 2960,
    weeklyDeliveryAmount: 9.3,
    amountDelivered: 58.5,
    costConsumed: 8.1,
    qualityPass: 86,
    clientScore: 4.1,
    riskLevel: '黄',
    riskDesc: '客户标准逐步清晰，但通过率仍未完全回到目标区间。',
    blockerTitle: '供应商培训闭环验证',
    blockerStatus: 'open',
    blockerDueDate: '2026-04-23',
    suggestedAction: '继续做供应商培训闭环，并准备一轮验收样本复盘。',
    supplierName: '供应商甲',
    supplierHeadcount: 10,
    supplierQuality: 86,
    supplierOtdRate: 83,
    supplierCooperation: 85,
    supplierIssue: '质量改善中，但准时率仍需继续盯。',
    algoVersion: 'v1.1',
    modificationRate: 18,
    timeSavePct: 24,
    algoAdvice: '优先优化车道线断点和特殊场景误判。',
    hoursSpent: 40,
    pmHourlyCost: 180,
    pmComment: '风险尚未完全解除，当前以质量提升为第一优先级。',
    nextWeekFocus: '1. 训练供应商 2. 盯客户验收 3. 继续提升准时率',
    status: 'draft',
    createdAt: '2026-04-17T08:00:00.000Z',
    updatedAt: '2026-04-20T03:15:00.000Z',
  },
  {
    id: 'pmr-003',
    projectId: 'P002',
    projectName: 'Mary',
    pmName: '郑威格',
    curveType: '二曲线',
    annotationType: '里程碑',
    plannedQty: 5,
    qtyUnit: '个里程碑',
    budgetTotal: 180,
    weekStart: '2026-04-14',
    progressPct: 86,
    actualQty: 4,
    weeklyDeliveryAmount: 0,
    amountDelivered: 0,
    costConsumed: 128.5,
    qualityPass: 100,
    clientScore: 4.1,
    riskLevel: '黄',
    riskDesc: '格式适配工期偏移，算法联动风险还在持续跟踪。',
    blockerTitle: '格式适配工期偏移',
    blockerStatus: 'watching',
    blockerDueDate: '2026-04-22',
    suggestedAction: '拆分问题单，后端和算法并行推进，避免同一责任链阻塞。',
    supplierName: '内部研发',
    supplierHeadcount: 0,
    supplierQuality: 100,
    supplierOtdRate: 100,
    supplierCooperation: 100,
    supplierIssue: '无供应商异常',
    algoVersion: 'v1.3',
    modificationRate: 12,
    timeSavePct: 36,
    algoAdvice: '维持版本稳定，重点观察格式适配回归情况。',
    hoursSpent: 24,
    pmHourlyCost: 180,
    pmComment: '下周需要把 Blocker 进一步拆细，保证里程碑稳定推进。',
    nextWeekFocus: '1. 清理 Blocker 2. 联调回归 3. 输出老板可读摘要',
    status: 'draft',
    createdAt: '2026-04-18T06:10:00.000Z',
    updatedAt: '2026-04-20T02:00:00.000Z',
  },
];

export const demoPmReportsStore: PmWeeklyReportsStore = {
  projects: demoPmProjects,
  reports: demoPmReports,
};

